### ISSUE TITLE
pyvista doesn't show the plot the 2nd time it is run in a script

### ISSUE THREAD

**Issue by maxcapodi78** [pyvista/pyvista#1260]
When running a python script which plot different  3D models pyvista plots it correctly the first time you run the code. the 2nd time the image quickly shows and then close it automatically

-----

**To Reproduce**

```py
import pyvista as pv
def show():
    sphere = pv.Sphere()
    plotter = pv.Plotter()
    plotter.add_mesh(sphere)
    plotter.show()
show()
show()
```

**Comment by tkoyama010** [comment]
Could you run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

**Comment by akaszynski** [comment]
@maxcapodi78, I'll get on this today.  It's been a busy week already, but I'll try to get this out.  I've been able to duplicate this locally on windows as well.

**Comment by akaszynski** [comment]
See #186, #1018 and #1078 for other issues related to this one.  This is a reoccurring issue and is cited in `plotter.py`

**Comment by akaszynski** [comment]
Fixed in #1266.  Release 0.30.0 might not be out by the end of the week, so we're releasing 0.29.1 since this makes `pyvista` unusable beyond one plot on windows.

**Comment by u-anurag** [comment]
I still have issues with the plot window. The plot shows up and the window closes instantly. Here is the example,


```python
import pyvista as pv
p = pv.Plotter()
box = pv.Cube(bounds=(-3,3,-5,6,50,75))
p.add_mesh(box, color=True,show_edges=True)
p.show()
```


I have already updated the installation to v0.29.1. Here is the warning,

![image](https://user-images.githubusercontent.com/35711550/116119772-054cb200-a67c-11eb-94ce-780b79a056fe.png)

Here is the report outcome using

```python
import pyvista as pv
print(pv.Report())
```

![image](https://user-images.githubusercontent.com/35711550/116119935-34fbba00-a67c-11eb-906a-34b07b7b4687.png)

The window works fine when I comment out lines 4390 and 4391 in the `plotting.py` file.

**Comment by akaszynski** [comment]
This might be an issue with `vtk==8.1.2`.  I'm assuming you're using the one available from anaconda that's not up on pypi.  Can you check on 8.1.2 or 9.0?  I'll know how to attack this going forward.

Opening until this is resolved.

**Comment by u-anurag** [comment]
I ran the code with `vtk=9.0` and the plotter works just fine. I think it is an issue with `vtk=8.2`. Here is the report output,

![image](https://user-images.githubusercontent.com/35711550/116188179-2cd76500-a6e4-11eb-9b79-65f91807f901.png)
