### ISSUE TITLE
pyvista rendering on online jupyter notebooks

### ISSUE THREAD

**Issue by wawosz** [pyvista/pyvista#313]
Every time when I run a simple pyvista example (below) for rendering in jupyter notebook online at [notebooks.azure.com](notebooks.azure.com), [colab.research.google.com](colab.research.google.com) or my own jupyterHub server, kernel dies and restarts but no rendering is done. All works fine on a standard jupyter notebook run from the command line. What it could be?

```py
import pyvista as pv
sphere = pv.Sphere()

# short example
cpos, image = sphere.plot(notebook=True)

# long example
plotter = pv.Plotter(notebook=True)
plotter.add_mesh(sphere)
plotter.show()
```

**Comment by akaszynski** [comment]
Ran into this issue as well.  The trick is setting up the headless display:

Divide this up into three cells.  Wish I could figure out how to link the colab I just built.

```python
# setup enviornment for interactive plotting
!apt-get install -qq xvfb
!pip install pyvista panel -q

import os
os.system('/usr/bin/Xvfb :99 -screen 0 1024x768x24 &')
os.environ['DISPLAY'] = ':99'

import panel as pn
pn.extension('vtk')



### new cell simple plot ###
pn.extension('vtk')  # this needs to be at the top of each cell for some reason
import pyvista as pv
sphere = pv.Sphere()
sphere.plot(color='w', notebook=True)



### new cell spline example cell ###
pn.extension('vtk')  # this needs to be at the top of each cell for some reason

import numpy as np

n_points = 100
theta = np.linspace(-4 * np.pi, 4 * np.pi, n_points)
z = np.linspace(-2, 2, n_points)
r = z ** 2 + 1
x = r * np.sin(theta)
y = r * np.cos(theta)
points = np.column_stack((x, y, z))

# Create spline with 1000 interpolation points
spline = pv.Spline(points, 1000)

# add scalars to spline and plot it
spline["scalars"] = np.arange(spline.n_points)
tube = spline.tube(radius=0.1)
tube.plot(smooth_shading=True, notebook=True)
```

**Comment by wawosz** [comment]
Worked like charm in Google Colab and my own jupyterhub server. Thank you!
In notebooks.azure.com, `!apt-get install -qq xvfb` gives permission error (apparently Azure does not allow installing packages). Anyway, at least Google Colab worked great.

**Comment by akaszynski** [comment]
> Worked like charm in Google Colab and my own jupyterhub server. Thank you!
> In notebooks.azure.com, `!apt-get install -qq xvfb` gives permission error (apparently Azure does not allow installing packages). Anyway, at least Google Colab worked great.

This appears to be a known issue: https://github.com/microsoft/AzureNotebooks/issues/695.  I'm sure they'll add support for it eventually.

Even though this was solved, I'm going to keep the issue open so when we add additional support for panel plotting, we remember to document a demo of it on Google Colab.

**Comment by gcapu** [comment]
@akaszynski It seems that the colab example is not there anymore.

**Comment by yohanesnuwara** [comment]
Hi @akaszynski 

When I did this step in Google Colab: 
```
# setup environment for interactive plotting
!apt-get install -qq xvfb
!pip install pyvista panel -q
```
I came across this error message:
```
ERROR: chainer 6.5.0 has requirement typing-extensions<=3.6.6, but you'll have typing-extensions 3.7.4.2 which is incompatible.
```
Then, I import the panel `pn`:
```
import panel as pn
```
This error message came out:
```
ImportError: cannot import name 'future_add_done_callback'
```
How to solve this issue? 

Regards, 

Nuwara

**Comment by akaszynski** [comment]
Try: https://forum.humanbrainproject.eu/t/jupyter-collab-storage-has-problem-with-latest-tornado-package/571

**Comment by gcapu** [comment]
@yohanesnuwara @akaszynski 
Here I made it work in colab using pyvirtualdisplay. You don't need to add the extension vtk thing in every block.

[colab notebook](https://colab.research.google.com/drive/1kKgc2Jc9SIa20PqGLWCepKebcGUUIbEP?usp=sharing)

```python
!pip install -q piglet pyvirtualdisplay
!pip install -q pyvista
!apt-get -qq install xvfb

# new cell
from pyvirtualdisplay import Display
display = Display(visible=0, size=(600, 400))
display.start()

# new cell
import pyvista as pv
sphere = pv.Sphere()
# short example
sphere.plot(notebook=True, window_size=(600,400))

# new cell
# long example
plotter = pv.Plotter(notebook=True, window_size=(600,400))
plotter.add_mesh(sphere)
plotter.show()
```

**Comment by banesullivan** [comment]
Nice work, @gcapu! Also, it may be worth experimenting with https://github.com/Kitware/ipyvtk-simple too

**Comment by theSubsurfaceGuy** [comment]
> @yohanesnuwara @akaszynski
> Here I made it work in colab using pyvirtualdisplay. You don't need to add the extension vtk thing in every block.
> 
> [colab notebook](https://colab.research.google.com/drive/1kKgc2Jc9SIa20PqGLWCepKebcGUUIbEP?usp=sharing)
> 
> ```python
> !pip install -q piglet pyvirtualdisplay
> !pip install -q pyvista
> !apt-get -qq install xvfb
> 
> # new cell
> from pyvirtualdisplay import Display
> display = Display(visible=0, size=(600, 400))
> display.start()
> 
> # new cell
> import pyvista as pv
> sphere = pv.Sphere()
> # short example
> sphere.plot(notebook=True, window_size=(600,400))
> 
> # new cell
> # long example
> plotter = pv.Plotter(notebook=True, window_size=(600,400))
> plotter.add_mesh(sphere)
> plotter.show()
> ```

Hi @gcapu , I'm trying to run the following example on Colab but the I couldn't see the plot.

The example I'm trying to reproduce
https://docs.pyvista.org/examples/00-load/create-uniform-grid.html#sphx-glr-examples-00-load-create-uniform-grid-py

The Colab notebook
https://colab.research.google.com/drive/1oaFUl8lifNbmgerC_OBXzhEIHeOuibIq?usp=sharing

Really appreciate your time and assistance in this regard.

**Comment by gcapu** [comment]
if you change the last line to 
```
grid.plot(show_edges=True, notebook=True, window_size=(600,400))
```
it works fine.

**Comment by PatrickPuente** [comment]
@gcapu Hola German tal vez me podrias ayudar ... mira te comento soy muy nuevo con la libreria pyvista y estoy aprendiendo por mi cuenta así que utilizaba Google Colab pero no puedo graficar este modelo 3D de un conejo y me dice que tengo error en la parte de: 
             mesh = examples.download_bunny_coarse()

Encontre una guia introductoria en la pagina de pyvista, pero no puedo correr este pequeño código en google colab, te dejo una foto del codigo que quiero correro. Por fa ayuda ...

![image](https://user-images.githubusercontent.com/56802138/99209358-fc80b780-2790-11eb-857f-23efca2fa092.png)

**Comment by gcapu** [comment]
@PatrickPuente disculpá, dónde econtraste ese ejemplo? Si podés, en lugar de pegar la imagen es mejor si pegás el código, así lo puedo correr y ver donde está el problema. 
Igual, como sos nuevo, te recomiendo que al principio no uses Pyvista en Colab ya que requiere un poco de trabajo extra. Si usás Jupyter lab, el código en el sitio debería funcionar sin inconvenientes. 

PS: Se habla español!

**Comment by PatrickPuente** [comment]
@gcapu claro aquí te dejo el link, es una presentación y el codigo está en la quinta diapositivia:

https://docs.google.com/presentation/d/1M_cnS66ja81u_mHACjaUsDj1wSeeEtnEevk_IMZ8-dg/edit#slide=id.g91152716fe_1_0

Pero bueno aquí te dejo también el código completo (es una pequeñes):

import pyvista as pv
from pyvista import examples

mesh = examples.download_bunny_coarse()
cpos = [(0.2, 0.3, 0.9), (0, 0, 0), (0, 1, 0)]
mesh.plot(cpos=cpos, show_edges=True, color=True)

Gracias por responder y en español jaja que golaso 👍

**Comment by gcapu** [comment]
@PatrickPuente, acá lo tenés:
[colab notebook](https://colab.research.google.com/drive/11o9eohQsrqRHoq_7PeBL3RuhKtO8-Wgo?usp=sharing)

Fijate los primeros bloques. En colab los tenés que poner al principio para que inicie un par de cosas necesarias. Otra cosa es agregar lo de "notebook=True" en la ultima linea.

**Comment by gcapu** [comment]
Glad to help, but I need to give a little disclaimer. I'm not associated with this project in any way. I'm not a contributor and I don't know any of the people that work on it. It is a great project so I like to help with what I can, but my answers may be outdated and they are definitely not official solutions.

**Comment by francesco-ballarin** [comment]
Hi,
I am trying several of the notebooks posted above, but none of them seems to be working for me with the latest pyvista release.

Furthermore, can I ask for clarifications on the following excerpt from https://docs.pyvista.org/user-guide/jupyter/index.html?
```
However, on Google Colab, where it’s not possible to install system packages,
you should stick with a module like threejs,
which does not require any server side rendering or framebuffer.
```
* I do not get what `it’s not possible to install system packages` means: you are the root user on Colab, you can install further packages with "!apt install", as many of the posts above as shown.
* `you should stick with a module like threejs`: I tried using `ipygany` (even as a standalone package, creating a `ipygany.Scene`) and no output is shown. I wonder if this sentence is still up to date.

**Comment by akaszynski** [comment]
> I do not get what it’s not possible to install system packages means: you are the root user on Colab, you can install further packages with "!apt install", as many of the posts above have shown.

Clearly whoever wrote this (me) didn't realize that you can install system packages on Google Colab...

> I tried using ipygany (even as a standalone package, creating a ipygany.Scene) and no output is shown. I wonder if this sentence is still up to date.

You might have issues with this depending on the version of juptyerlab used.  I've had where I've had to make a virtual env with a clean install locally to get it to work.

@banesullivan, when you get a second (which is doubtful), can you take a look at why our examples aren't working?

**Comment by francesco-ballarin** [comment]
Thanks @akaszynski for your reply!

> You might have issues with this depending on the version of juptyerlab used.
I believe that Colab is still based on Jupyter, not JuypterLab.

**Comment by akaszynski** [comment]
Running some brief tests on colab shows that it's not rendering anything except for static images.  My guess is that you'll need a jupyterlab environment for anything but `jupyter_backend='static'` to work.

**Comment by francesco-ballarin** [comment]
Support for custom widgets seems to be possible now on Colab, using
```
from google.colab import output
output.enable_custom_widget_manager()
```
see https://github.com/googlecolab/colabtools/issues/498

With such support enabled, `pyvista.PlotterITK` is correctly (with regards to display & interactivity) showing on Colab for me.

**Comment by banesullivan** [comment]
Hi everyone, I'm going to close this issue because I believe it has been mostly resolved in recent efforts. The MyBinder environment should be working stably at this point and we are also now shipping pre-built Docker images through GitHub's container registry with Jupyter Lab set up for PyVista and its notebook rendering backends:

See https://github.com/pyvista/pyvista/pkgs/container/pyvista and https://github.com/pyvista/pyvista/tree/main/docker

Further, @akaszynski has been working hard to ship OSMesa versions of VTK in https://github.com/pyvista/pyvista-wheels to mitigate any issues with setting up a headless display in these environments. I'd like to ask that if you are still having issues with online Jupyter notebook rendering to please open a new issue

**Comment by mobigroup** [comment]
The ticket is closed but PyVista still does not work on Google Colab and never works before for me, some updates?

**Comment by mobigroup** [comment]
The suggestions above are not valid:

```
from google.colab import output
output.enable_custom_widget_manager()
p = pv.PlotterITK()
```
AttributeError: module 'pyvista' has no attribute 'PlotterITK'

```
# install and configure virtual display for vtk
import sys
if 'google.colab' in sys.modules:
  !apt-get -qq install xvfb
  !{sys.executable} -m pip install -q piglet pyvirtualdisplay
  !{sys.executable} -m pip install -q pyvista

  from pyvirtualdisplay import Display
  display = Display(visible=0, size=(600, 400))
  display.start()

...

zscale = 5

p = pv.Plotter()

da = density.sel(x=slice(-xsize,xsize), y=slice(-xsize,xsize)).copy()
grid = da2UniformGrid(da)
p.add_mesh(grid.outline(), color="k")
contours = grid.contour(isosurfaces=10, scalars="density")
p.add_mesh(contours.clip(normal='y', invert=True), opacity=1,  ambient=0.2, show_scalar_bar=False)
p.add_mesh(contours.clip(normal='y', invert=False), opacity=0.5, ambient=0.2, show_scalar_bar=False)
mesh = grid.slice_orthogonal()
p.add_mesh(mesh, opacity=0.5, ambient=0.2, show_scalar_bar=False)

da = gravity.sel(x=slice(-xsize+4*downscale,xsize), y=slice(-xsize+4*downscale,xsize))
mesh = da2StructuredGrid(zscale*(1+da))
p.add_mesh(mesh, opacity=.2, style='wireframe', line_width=2, lighting=False, ambient=1, show_scalar_bar=False)

p.show_axes()
p.add_title(f'Synthetic Density Model and its Gravity\nScale 1:{downscale} Gaussian Filter Sigma {np.round(sigmas).astype(int)}', font_size=24)
p.show()
```
This code runs infinite time and kills the running Colab kernel.

**Comment by banesullivan** [comment]
Google colab is a tough platform to support. The PlotterITK has been removed from PyVista. Support for PyVista's latest Jupyter backend on Colab is tracked here: https://github.com/pyvista/pyvista/issues/3851

**Comment by mobigroup** [comment]
Ok, thanks. So that still not supported although announced lots of times…

**Comment by banesullivan** [comment]
If you want to use itkwidgets directly, it has support for Google Colab and great interoperability with PyVista mesh objects: https://github.com/InsightSoftwareConsortium/itkwidgets

**Comment by banesullivan** [comment]
We removed PlotterITK because its better to just use itkwidgets directly in those use cases as there is not a mapping between PyVista's Plotter and itkwidgets

**Comment by mobigroup** [comment]
@banesullivan Unfortunately, Pyvista does not work with itkwidgets too:

```
import pyvista.examples
itkwidgets.view(geometries=pyvista.examples.load_hexbeam())
```
<img width="1865" alt="image" src="https://user-images.githubusercontent.com/7342379/222097882-6a2ce05f-b25e-4ba9-b640-085e63ce08fa.png">

**Comment by banesullivan** [comment]
@mobigroup, I'd recommend opening an issue directly with itkwidgets for that. AFAIK, that *should* work

**Comment by mobigroup** [comment]
@banesullivan I've tried itkwidgets examples and these are not work on Google Colab. I’m just ask is there some way to use PyVista on Google Colab or we need to call VTK directly and use other libraries visualize the data? I've made some open source example using PyVista years ago and I still cannot to show them on Google Colab although PyVista developers again and again promising that it will work soon, that's so disappointing...

**Comment by banesullivan** [comment]
> I've tried itkwidgets examples and these are not work on Google Colab
 
itkwidgets works on Google Colab with the latest dev release: https://github.com/InsightSoftwareConsortium/itkwidgets#google-colab

It's likely you're using itkwidgets `0.32.5` but need the alpha 1.x release: https://pypi.org/project/itkwidgets/#history

For itkwidgets support, please open an issue there: https://github.com/InsightSoftwareConsortium/itkwidgets/issues/new

> I’m just ask is there some way to use PyVista on Google Colab or we need to call VTK directly and use other libraries visualize the data?

You don't need to step back to using VTK directly in this scenario -- because PyVista *is* VTK. The best way to use PyVista on Colab is to leverage a 3rd party library for the end rendering at this time. Otherwise, you can use PyVista's `static` backend on Colab for static screenshots of the renderings. Unfortunately, interactive rendering support on Colab for PyVista is blocked until Colab allows web socket connections; see https://github.com/pyvista/pyvista/issues/3851 and https://github.com/googlecolab/colabtools/issues/2529. Until then, this is primarily out of our hands.

>  still cannot to show them on Google Colab although PyVista developers again and again promising that it will work soon, that's so disappointing...

I apologize for misleading you about our ability to support Google Colab fully. PyVista has historically been developed on a volunteer basis, and our contributors cannot support every cloud computing platform. We support most local and cloud Jupyter environments, but our bandwidth is finite. 

**If you are interested in funding development of PyVista to bring further PyVista support to Google Colab, I would like to encourage you to reach out to kitware@kitware.com to work with us to address this. Details can be found at https://github.com/pyvista/pyvista/discussions/4033**

**Comment by mobigroup** [comment]
@banesullivan The example notebooks updated recently and include the required library version installation command:
```
!{sys.executable} -m pip install -q "itkwidgets[all]>=1.0a23"
```

But the notebooks do not work and even code is not compatible to the library, see https://github.com/InsightSoftwareConsortium/itkwidgets/blob/main/examples/NumPyArrayPointSet.ipynb
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/7342379/222383281-fba3f05f-8276-4377-8bca-a431a8fc8799.png">

https://github.com/InsightSoftwareConsortium/itkwidgets/blob/main/examples/Hello3DWorld.ipynb
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/7342379/222384475-8dd95014-5842-4804-8478-e11d09e92940.png">

The project looks as a fake.

> PyVista is VTK

As I understand PyVista is Python-coded VTK wrapper, is not it?
```
pip3.10 install pyvista
...
Requirement already satisfied: vtk in /opt/homebrew/lib/python3.10/site-packages (from pyvista) (9.2.5)
...
```

> Otherwise, you can use PyVista's static backend on Colab for static screenshots of the renderings.

It does not work too because PyVista plotter object crashes for 'static' backend as for pythreejs, ipygany, panel:
```
!{sys.executable} -m pip install -q pyvista pythreejs ipygany panel
!sudo apt install libgl1-mesa-glx xvfb
import pyvista as pv
pv.set_jupyter_backend('static')
pv.start_xvfb()

...
p = pv.Plotter()
...
p.show()
```

And ipygany requires virtual framebuffer while it is documented as '...does not require a virtual framebuffer' https://docs.pyvista.org/user-guide/jupyter/index.html:
```
/usr/local/lib/python3.8/dist-packages/pyvista/plotting/plotting.py:147: UserWarning: 
This system does not appear to be running an xserver.
PyVista will likely segfault when rendering.

Try starting a virtual frame buffer with xvfb, or using
  ``pyvista.start_xvfb()``
```

Is it possible to make even static image using PyVista on Google Colab?

**Comment by francesco-ballarin** [comment]
Hi @mobigroup,
as author of https://github.com/pyvista/pyvista/issues/3851, I very much look forward to trame support on Colab.

Still, until that day comes I had to look for other workarounds: I was able to get `ipygany` working, see
https://colab.research.google.com/github/fem-on-colab/fem-on-colab.github.io/blob/gh-pages/tests/vtk/test-pyvista.ipynb
(just notice that you will have to run the first cell twice, and the first time it will make the kernel crash on purpose: this is unrelated to pyvista, and due to https://github.com/googlecolab/colabtools/issues/3397)

You probably don't want to pull in all my dependencies just for this, but you may want to apply the same patch I have in my project, namely
https://github.com/fem-on-colab/fem-on-colab/blob/main/vtk/patches/01-ipygany
* the first patch is to avoid annoying my users with the deprecation warning, since I would love to use the non-deprecated trame, but it does not work yet
* the second patch is to automatically start xvfb
* the third patch is to remove the dropdown to change the colorbar: `jslink` does not seem to work at all on colab
* the fourth patch is to switch from trame to ipygany by default

You may also want to add this line
https://github.com/fem-on-colab/fem-on-colab/blob/main/base/bin/enable_widgets.py#L22
before importing pyvista.

Let me know if that helps.

**Comment by mobigroup** [comment]
@francesco-ballarin Thanks, your notebook works! By the way, the installation and configuration look too complicated, see the updated version: https://colab.research.google.com/drive/1wbgfx9aNZEgq4nittf2sc68ngeexKf1Y?usp=sharing

<img width="1841" alt="image" src="https://user-images.githubusercontent.com/7342379/222414040-d175c433-3f94-4b40-add5-5671df3796bc.png">

I think the colormap selector is a useful tool so we do not need to remove it (yes, it works).

**Comment by mobigroup** [comment]
@banesullivan @francesco-ballarin 

Maybe do you have some ideas why the 2nd example below does not work using ipygany backend? It works well using 'static' backend.
 
```
p = pv.Plotter(notebook=True)

da = density.sel(x=slice(-xsize,xsize), y=slice(-xsize,xsize)).copy()
grid = da2UniformGrid(da)
#mesh = grid.slice_orthogonal()
p.add_mesh(grid)

p.show(jupyter_backend="ipygany", return_viewer=True)
```

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/7342379/222435739-87c86f83-141f-421c-9b91-8d840b9e7238.png">

```
p = pv.Plotter(notebook=True)

da = density.sel(x=slice(-xsize,xsize), y=slice(-xsize,xsize)).copy()
grid = da2UniformGrid(da)
mesh = grid.slice_orthogonal()
p.add_mesh(mesh)

p.show(jupyter_backend="ipygany", return_viewer=True)
```

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/7342379/222435926-fbb6abe6-05ac-46e5-bed1-3c30dd2f7848.png">


The mesh is PyVista object as expected:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/7342379/222436432-062ef27d-831e-4ce5-914a-61d59daab88b.png">

**Comment by francesco-ballarin** [comment]
Thanks @mobigroup for reporting that I can simplify some of my patches. I believe that the colorbar change was not working till a few days ago because Colab shipped an ancient version of matplotlib, but this is now fixed by https://github.com/googlecolab/colabtools/issues/3428.


I'll try having a look at your other cases in a few hours, but it would probably be helpful if you add them to the existing notebook so that we can easily copy and paste. In the meantime, can you try running those same notebooks on your local installation? That could be helpful in filtering out which errors are due to Colab, and which would also show in a standard installation.

**Comment by mobigroup** [comment]
@francesco-ballarin Yes, the Matplotlib upgrade resolves lots of issues. By the way, we can use 'turbo' colormap instead of outdated 'jet' now.

The notebooks with the cases is public: https://colab.research.google.com/drive/1de2GcRBkQIGzFG1cqZRhDJ9DsR2ZHqKx?usp=sharing

Now it works using 'static' backend only. 
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/7342379/222492714-5ac4f037-1baf-4271-a0e3-60af641d9f70.png">

The notebook firstly shared on GitHub years ago: https://github.com/mobigroup/gis-snippets/blob/master/Synthetic%20Model%20Inversion/basic.ipynb It always worked locally but I couldn't adopt it to Google Colab Python 3.7 and outdated libraries. For this year Google Colab upgraded to Python 3.8 and we have a chance to resolve the old compatibility problems I hope.

**Comment by francesco-ballarin** [comment]
I am able to make that notebook work, with just a few changes:
* replace `mesh = grid.slice_orthogonal()` with `mesh = grid.slice_orthogonal().combine()`
* replace the `seismic` colormap with one from `ipygany`
* give up on using wireframe, since
```/usr/local/lib/python3.8/dist-packages/pyvista/jupyter/pv_ipygany.py:130: UserWarning: Wireframe style is not supported in ipygany
  warnings.warn('Wireframe style is not supported in ipygany')```

**Comment by mobigroup** [comment]
@francesco-ballarin Thanks, it works although all the axes and coordinates box are missed. Anyway, we cannot use it due to frequent background tiles (black polygons) flickers as for default background as for white:

<img width="1802" alt="image" src="https://user-images.githubusercontent.com/7342379/222635630-c0bb84e9-83b8-41cc-94a3-f4ca5454b9eb.png">

<img width="627" alt="image" src="https://user-images.githubusercontent.com/7342379/222635785-d45dbf02-bc8c-4082-92fa-7bdd91ee4e2e.png">

**Comment by francesco-ballarin** [comment]
Hi @mobigroup,
should I do anything specific to see the background flickers? I moved the plot around, zoomed in/out for quite a while, but never got one. I am on chrome on debian.

The fact that axes and coordinate boxes are missing is probably a limitation of the `ipygany` backend (cc @banesullivan). If that is the case, it is unlikely it will ever get fixed, considering that any non-`trame` backend is deprecated.

@mobigroup, you are welcome to add a message to https://github.com/googlecolab/colabtools/issues/2529 saying e.g. that you are looking forward to seeing the issue fixed for use within pyvista. It may not make much of difference, but at the very least this way you will get notified about new replies ;)

**Comment by mobigroup** [comment]
@francesco-ballarin  I’m just moving a mouse pointer on top of the image or scroll the page and there are a lot of flickers. My browser is the up-to-date Safari on MacOS.

Ok, I've found the issue source:
```
p.add_mesh(grid.outline(), color="k")
```

But it looks as ipygany has no opacity support and allows only 'surface' style ('points' style produces just strange noise):

<img width="670" alt="image" src="https://user-images.githubusercontent.com/7342379/222645959-6e491754-089b-4040-b66b-fa553badd218.png">

'static' backend result is much better:

<img width="963" alt="image" src="https://user-images.githubusercontent.com/7342379/222646336-90097bc5-818b-4c80-80ec-29751e3d29ed.png">


My models should look like to this one below (https://www.youtube.com/watch?v=ZVWKQCxPLlI) so I think ipygany backend is not my choice, obviously:

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/7342379/222646229-f29ee82d-8edd-4ad3-9bef-b04d43b989f5.png">

**Comment by francesco-ballarin** [comment]
you may want to try with `panel` instead then. Definitely not with `pythreejs` due to https://github.com/googlecolab/colabtools/issues/3159

**Comment by mobigroup** [comment]
Yes, I’m checking ‘panel’ too. Actually, it looks to be good to be truth and works much smoother than on top Google Cloud instances a year ago :)

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/7342379/222663692-9f1e4dde-adb8-4407-bf71-8f0e12edae2f.png">

**Comment by francesco-ballarin** [comment]
Good to know, if panel works for you I'll try switching to that myself!

**Comment by francesco-ballarin** [comment]
I can confirm that I have switched to `panel`. @banesullivan, is this use case enough of a reason to keep the deprecated `panel` backend around until https://github.com/pyvista/pyvista/issues/3851 is sorted? I wouldn't want to go back to not having any usable backend on Colab once v0.39 is released on April 30, 2023 :(

**Comment by banesullivan** [comment]
> is this use case enough of a reason to keep the deprecated panel backend around until https://github.com/pyvista/pyvista/issues/3851 is sorted? I wouldn't want to go back to not having any usable backend on Colab once v0.39 is released on April 30, 2023 :(

This is something the development team will have to hash out

**Comment by francesco-ballarin** [comment]
Hi @banesullivan @mobigroup ,
since April 30 is getting closer and it is critical for my teaching that `pyvista` on Colab will continue to work after that date, I am willing to try out the following:
https://github.com/viskex/viskex/commit/8895f22213cf341ca740031fa0c12dbe0ff7d556#diff-afc140ae1d6f116232d7927a2f17138664632e2c372bd188481cdaa548edbb12R228
which basically ships a slightly simpler version of the current implementation of the `panel` backend within my own library.

Do you that this could be a sensible approach going forward from v0.39 onwards?
If so, I'd like to inquire if there is any relationship/reciprocity between `pyvista` developers and `panel` developers, i.e. if `pyvista` support within `panel` was added due to your request, or if it was already there. I guess that the rationale of my question is that I am trying to estimate if `pyvista` dropping the `panel` backend will also mean that `panel` will drop `pyvista`/`vtk` support, or if (at least to the best of your knowledge) the two facts are reasonably unrelated and I can rely on `panel` until https://github.com/pyvista/pyvista/issues/3851 is sorted out.

Thanks!

**Comment by banesullivan** [comment]
> which basically ships a slightly simpler version of the current implementation of the panel backend within my own library. ... Do you think that this could be a sensible approach going forward from v0.39 onwards?

Excellent! IMO, this is preferred.

> I'd like to inquire if there is any relationship/reciprocity between pyvista developers and panel developers, i.e. if pyvista support within panel was added due to your request, or if it was already there

There is not -- these things are completely independent. Panels' support for PyVista/VTK only furthers my justification for the deprecation of PyVista panel implementation.

> I am trying to estimate if pyvista dropping the panel backend will also mean that panel will drop pyvista/vtk support

It will not -- though, AFAIK, no one is actively maintaining or championing the VTK support previously added in Panel.

----

Overall, I think your approach is the way to go if you are stuck with Colab and want to use Panel

**Comment by francesco-ballarin** [comment]
Thanks @banesullivan !

Then, I withdraw my previous question

> is this use case enough of a reason to keep the deprecated panel backend around until #3851 is sorted?

and I agree with @banesullivan that that is actually a reason to *remove* the panel backend (alongside every other deprecated backend), rather than keeping it around ;)

**Comment by mobigroup** [comment]
Hi @francesco-ballarin @banesullivan Do you have some updates maybe? The solution discussed above no longer works on Google Colab, so I've made some modifications to revive it. See interactive PyVista plots on Google Colab for use cases in my satellite interferometry project: https://github.com/mobigroup/gmtsar


![](https://user-images.githubusercontent.com/7342379/280690307-d2eda089-0730-4699-82db-9410712d55ff.png)

**Comment by francesco-ballarin** [comment]
I clicked on a couple of links in the repository, and it seems to me that you are using panel directly. That's what I am currently doing as well.

However, I am affected by https://github.com/holoviz/panel/issues/5809 
Can you check if colorbars appear correctly in your code and, if not, bump the issue there?

**Comment by banesullivan** [comment]
> Do you have some updates maybe? The solution discussed above no longer works on Google Colab

Our support for CoLab is tracked in https://github.com/pyvista/pyvista/issues/3851. The TL;DR: CoLab does not allow WebSocket connections so our Jupyter backend will not work there at this time, which is tracked in https://github.com/googlecolab/colabtools/issues/2529

There is some work going on in https://github.com/Kitware/trame-jupyter-extension to leverage the JupyterComms infrastructure for our trame-based backend, which is tracked in https://github.com/pyvista/pyvista/issues/5001#issuecomment-1749890480

**Comment by francesco-ballarin** [comment]
@banesullivan I don't exepct https://github.com/Kitware/trame-jupyter-extension will be of much help with Colab (or similar online jupyter providers, such as kaggle.com), as they do not allow to install your custom extensions. Furthermore, I believe that Colab is still based on the old jupyter notebook rather than jupyter lab.

Still, do you think that https://github.com/Kitware/trame-jupyter-extension could be helpful in supporting jupyter lite? If that is an idea you are willing to keep track of I can open an issue there as a reminder.
(of course that would also mean being able to compile VTK with emscripten, but that's a different beast)

**Comment by banesullivan** [comment]
>  as they do not allow to install your custom extensions

Well that'd be the limiting factor then. In this case, I don't think we will ever be able to have "official" support for Colab then... however one alternative could be to use the new "embeddable" backend coming in https://github.com/pyvista/pyvista/pull/5168 (this is effectively exporting the scene, so very limited compared to our default backend)
