### ISSUE TITLE
add_axes is not supported on trame client, and may even raise an error

### ISSUE THREAD

**Issue by francesco-ballarin** [pyvista/pyvista#4130]
Hi,
this issue can be split in two halves:
- [ ] when running e.g. in jupyter lab, `plotter.add_axes` seems not add anything to the figure with `trame` backend in `client` mode. 
- [x] ~when running in a headless environment, calling `plotter.add_axes` with `client` backend may cause a `AttributeError`.~ fixed by https://github.com/Kitware/trame-vtk/pull/30

To reproduce the latter, please create a new container
```
docker run -it --rm ubuntu:rolling
```
and install pyvista and a minimal set of dependencies
```
apt update
apt install python3-pip libgl1-mesa-glx xvfb vim
pip3 install ipywidgets nest_asyncio panel pyvista trame trame-vtk
```
Then run the following script
```
import traceback

import pyvista
import pyvista.examples

pyvista.start_xvfb()

mesh = pyvista.examples.download_st_helens().warp_by_scalar()

for jupyter_backend in ("client", "server", "panel"):
    for add_axes in (True, False):
        plotter = pyvista.Plotter(notebook=True)
        plotter.add_mesh(mesh)
        if add_axes:
            plotter.add_axes()
        print(jupyter_backend, add_axes)
        try:
            plotter.show(jupyter_backend=jupyter_backend, return_viewer=True)
        except:
            traceback.print_exc()
        else:
            print("OK")
```
to obtain the following output
```
client True
Traceback (most recent call last):
  File "//test.py", line 18, in <module>
    plotter.show(jupyter_backend=jupyter_backend, return_viewer=True)
  File "/usr/local/lib/python3.10/dist-packages/pyvista/plotting/plotting.py", line 6522, in show
    jupyter_disp = handle_plotter(self, backend=jupyter_backend, **jupyter_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pyvista/jupyter/notebook.py", line 55, in handle_plotter
    return show_trame(plotter, mode=backend, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pyvista/trame/jupyter.py", line 301, in show_trame
    viewer = initialize(
  File "/usr/local/lib/python3.10/dist-packages/pyvista/trame/jupyter.py", line 192, in initialize
    viewer.ui(
  File "/usr/local/lib/python3.10/dist-packages/pyvista/trame/ui.py", line 454, in ui
    view = PyVistaLocalView(self.plotter, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pyvista/trame/views.py", line 117, in __init__
    VtkLocalView.__init__(
  File "/usr/local/lib/python3.10/dist-packages/trame_vtk/widgets/vtk/common.py", line 778, in __init__
    self.update()
  File "/usr/local/lib/python3.10/dist-packages/trame_vtk/widgets/vtk/common.py", line 786, in update
    delta_state = MODULE.scene(self.__view, new_state=False)
  File "/usr/local/lib/python3.10/dist-packages/trame_vtk/modules/vtk/__init__.py", line 209, in scene
    scene_state = HELPER.scene(render_window, new_state)
  File "/usr/local/lib/python3.10/dist-packages/trame_vtk/modules/vtk/__init__.py", line 67, in scene
    return self._app.protocol_call(
  File "/usr/local/lib/python3.10/dist-packages/trame_server/core.py", line 416, in protocol_call
    return func(obj, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vtkmodules/web/protocols.py", line 827, in getViewState
    viewInstance = serializeInstance(
  File "/usr/local/lib/python3.10/dist-packages/vtkmodules/web/render_window_serializer.py", line 182, in serializeInstance
    return serializer(parent, instance, instanceId, context, depth)
  File "/usr/local/lib/python3.10/dist-packages/vtkmodules/web/render_window_serializer.py", line 1391, in renderWindowSerializer
    rendererInstance = serializeInstance(
  File "/usr/local/lib/python3.10/dist-packages/vtkmodules/web/render_window_serializer.py", line 182, in serializeInstance
    return serializer(parent, instance, instanceId, context, depth)
  File "/usr/local/lib/python3.10/dist-packages/vtkmodules/web/render_window_serializer.py", line 1258, in rendererSerializer
    viewPropInstance = serializeInstance(
  File "/usr/local/lib/python3.10/dist-packages/vtkmodules/web/render_window_serializer.py", line 182, in serializeInstance
    return serializer(parent, instance, instanceId, context, depth)
  File "/usr/local/lib/python3.10/dist-packages/trame_vtk/modules/vtk/addon_serializer.py", line 468, in axesActorSerializer
    actor.GetUserTransform().GetTranspose(matrix)
AttributeError: 'NoneType' object has no attribute 'GetTranspose'
client False
OK
server True
OK
server False
OK
panel True
OK
panel False
OK
```

**Comment by psavery** [comment]
It looks to me that the issue started occurring in `trame-vtk==2.3.0`. If I downgrade to `trame-vtk==2.2.3`, I don't encounter the issue.

**Comment by bilke** [comment]
I experience the same error in a headless environment, even with this simplest example:

```python
import pyvista as pv
sphere = pv.Sphere()
sphere.plot(jupyter_backend='trame') # same for client
```

Downgrading to `trame-vtk==2.2.3` helps for me too.

**Comment by carlosal1015** [comment]
Thanks, no errors with recent `trame-vtk` 2.3.5 and `pyvista` 0.38.4.
![image](https://user-images.githubusercontent.com/21283014/226774457-95059565-263d-445a-aaaa-684684a04f77.png)
But there will be a way to debug (infinite loop loading), because I suspect it doesn't work from Arch side due to downstream package issue in the dependencies of [`trame`](https://aur.archlinux.org/packages/python-trame).

**Comment by bilke** [comment]
For me on `jupyter_backend='trame'` it works.

When setting `jupyter_backend='client'` then I get the same wrong rendering as in https://github.com/Kitware/trame-vtk/issues/12#issuecomment-1468267813.

**Comment by francesco-ballarin** [comment]
> though the axes widget is still having some problem with client rendering

Are these the problems you are referring to?

![Screenshot from 2023-03-22 15-52-04](https://user-images.githubusercontent.com/11783908/226943620-aa6b971c-9a70-4ba1-87a1-c67f147e24d4.png)

**Comment by psavery** [comment]
This was fixed in kitware/trame-vtk#34

If you upgrade to `trame-vtk>=2.4.2`, you should see the fix. Note that you may need to clear your browser cache as well since it includes some javascript changes.

**Comment by banesullivan** [comment]
A little bit of work remains in PyVista to register these widgets with trame -- I'll handle this

**Comment by francesco-ballarin** [comment]
> This was fixed in https://github.com/Kitware/trame-vtk/pull/34

Not sure what "this" refers to.
I still see the same axes as in https://github.com/pyvista/pyvista/issues/4130#issuecomment-1479713958

Cleared the cached, even tried with a browser a never used with jupyter to be extra sure.

```
--------------------------------------------------------------------------------
  Date: Sat Apr 01 08:46:02 2023 CEST

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 15.3 GiB
       Environment : Python
       File system : ext4
        GPU Vendor : Intel
      GPU Renderer : Mesa Intel(R) UHD Graphics 620 (WHL GT2)
       GPU Version : 4.6 (Core Profile) Mesa 22.3.6

  Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]

           pyvista : 0.38.3
               vtk : 9.2.6
             numpy : 1.24.2
           imageio : 2.26.0
            scooby : 0.7.1
             pooch : v1.7.0
        matplotlib : 3.6.3
             PyQt5 : 5.15.9
           IPython : 8.11.0
        ipywidgets : 8.0.4
             scipy : 1.10.1
              tqdm : 4.64.1
            meshio : 5.3.4
        jupyterlab : 3.6.1
             trame : 2.3.2
      trame_client : 2.7.3
      trame_server : 2.9.1
         trame_vtk : 2.4.2
      nest_asyncio : 1.5.6
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment]
@francesco-ballarin, we still have some follow up work to do in PyVista to make the widgets work. This should be quick and I'll have done soon
