### ISSUE TITLE
split_bodies() generates a body that has 0 volume

### ISSUE THREAD

**Issue by kretes** [pyvista/pyvista#5613]
### Describe the bug, what's wrong, and what you expected.

After running `split_bodies` on a mesh that has a volume I expect returned bodies to have volume as well.

See [Colab](https://colab.research.google.com/drive/1P2xhRVPtCOCmpHWMbvbAD8u4o3tIQBMC?usp=sharing) for a reproduction. I have a single-component data that has volume == 0 in currentt pyvista.

See [Colab for pyvista 0.36.1](https://colab.research.google.com/drive/1g6RlzoXuupf8uGBqM_1IISqvAHLBTKtj?usp=sharing)  where it used to work 

### Steps to reproduce the bug.

```python

import pyvista
from pyvista import examples
dataset = examples.download_lucy()
print([(len(x.points), x.volume) for x in dataset.split_bodies()])
print(dataset.volume)
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Tue Feb 13 11:14:02 2024 UTC

                OS : Linux
            CPU(s) : 2
           Machine : x86_64
      Architecture : 64bit
               RAM : 12.7 GiB
       Environment : IPython
        GPU Vendor : Mesa
      GPU Renderer : llvmpipe (LLVM 15.0.7, 256 bits)
       GPU Version : 4.5 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1
  MathText Support : False

  Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

           pyvista : 0.43.3
               vtk : 9.3.0
             numpy : 1.23.5
        matplotlib : 3.7.1
            scooby : 0.9.2
             pooch : 1.8.0
            pillow : 9.4.0
           imageio : 2.31.6
           IPython : 7.34.0
          colorcet : 3.0.1
        ipywidgets : 7.7.1
             scipy : 1.11.4
              tqdm : 4.66.1
      nest_asyncio : 1.6.0
--------------------------------------------------------------------------------
```

**Comment by user27182** [comment]
Interesting. Checking the actual number of bodies with `n_blocks` shows that there is only one dataset in the multiblock.
``` python
import pyvista
from pyvista import examples
dataset = examples.download_lucy()
bodies = dataset.split_bodies()
print(bodies.n_blocks)  # 1
```


Also, under the hood this filter uses `connectivity` before splitting. If we do:

``` python
np.unique(dataset.connectivity()['RegionId'])
```
We get `[0]`, which confirms there is only one mesh returned by that function.

We can further confirm that the mesh returned by `split_bodies()` is that same as the dataset.
``` python
np.array_equal(dataset.connectivity().points, dataset.split_bodies()[0].points)  # True
```

So, it seems that there is definition just one mesh at the input and output.  Perhaps there is a bug with the `__contains__` method for `pv.MultiBlock`?

**Comment by user27182** [comment]
I think I misunderstood the bug, thinking that split_bodies was returning two messages, one of which had zero volume. But the bug is that `mesh.volume` returns zero when it should not? Is that correct @kretes ?

**Comment by user27182** [comment]
Looks like `threshold` is the likely culprit:

``` python
dataset.volume  # 81672476.45755768
dataset.connectivity().volume  # 81672476.45755768
dataset.connectivity().threshold([-1,1]).volume  # 0.0
```

I'm not sure what the cause is from `threshold`, perhaps it's a pyvista bug or a bug with the underlying vtk method.

But, as a workaround, the `connectivity` filter itself can be used to perform a similar operation as threshold, e.g. replace this line
https://github.com/pyvista/pyvista/blob/29a6c87802b1aca52218f2db4d4077680bae272a/pyvista/core/filters/data_set.py#L2881-L2882
and redefine the function as:

``` python
def split_bodies(mesh, label=False, progress_bar=False):
    conn = mesh.connectivity('all')
    conn_labels = conn.cell_data['RegionId']
    bodies = pyvista.MultiBlock()
    for vid in np.unique(conn_labels):
        # Now extract it:
        b = mesh.connectivity('specified', vid,  progress_bar=progress_bar)
        if not label:
            # strange behavior:
            # must use this method rather than deleting from the point_data
            # or else object is collected.
            b.cell_data.remove('RegionId')
            b.point_data.remove('RegionId')
        bodies.append(b)
    return bodies
```

calling `split_bodies(dataset)[0].volume` will return the correct (non-zero) volume

**Comment by kretes** [comment]
@user27182 yes - this is about the result of split_bodies having 0 volume while it should be non-zero.

**Comment by user27182** [comment]
I believe the issue stems from two things:

1. The input mesh is polydata, but threshold returns an unstructured grid
2. Volume for unstructured grids is calculated as the sum of the size of each cells. But triangle cells are 2D, which have zero volume, so the total volume of any unstructured grid with triangle cells is always zero. Volume for PolyData is therefore calculated differently.

So, there is no bug with the `volume` property or `threshold` filter in the sense that I believe they are working correctly. The issue is just that any `PolyData` -> `UnstructuredGrid` operation will result in non-zero volume meshes having zero-volume thereafter. Therefore, to preserve the volume we need a `PolyData` -> `PolyData` filter. 

The reason workaround function above works is because the `connectivity` filter handles polydata as a special case and is therefore a `PolyData` -> `PolyData` filter.

Since `threshold` and `split_bodies` return unstructured grids, @kretes you can try calling `extract_surface` after `split_bodies`, as suggested here https://github.com/pyvista/pyvista/issues/3009#issuecomment-1186545847 . Alternatively, you can use the function suggested above instead of `dataset.split_bodies`.

**Comment by user27182** [comment]
https://github.com/pyvista/pyvista/pull/5950 adds a new `method` param to `split_bodies` to allow using the `connectivity` filter internally. The issue of zero-volume can then be resolved with, e.g.:
``` python
import pyvista
from pyvista import examples
dataset = examples.download_lucy()
print(dataset.volume)  # 81672476.45755768

split_dataset = dataset.split_bodies(method='connectivity')
print(split_dataset.volume)  # 81672476.45755768
```

@kretes does this work for you?

**Comment by banesullivan** [comment]
For the closed surface case, this should be fixed with pyvista-manifold: https://github.com/pyvista/pyvista-manifold

```py
import pyvista as pv
from pyvista import examples
import pyvista_manifold  # noqa: F401

dataset = examples.download_lucy()
dataset.manifold.is_valid   # True
dataset.manifold.volume     # 81672476.46

parts = dataset.manifold.decompose()
for p in parts:
    print(p.n_cells, p.volume, p.manifold.is_valid)
# 99970, 81672476.46, True   (1 part, correct volume, type=PolyData)
```

`mesh.manifold.decompose()` returns each disjoint Manifold component as a fresh `pv.PolyData` (not an `UnstructuredGrid`), so `.volume` gives the correct mass-property answer and the result is ready to feed into anything
else. Requires the input be a closed surface.

**Comment by user27182** [comment]
Decompose is a good alternative in this case for `split_bodies`. I think the broader issue still remains: the geometric meaning of `volume` changes depending on the mesh type. And `PolyData` -> `UnstructuredGrid` is very common for filters.

I wonder if a better solution is to define a new property, `enclosed_volume`, which is implemented for _all_ mesh types as `extract_surface` -> `vtkMassProperties().GetVolume()`.

That way, we always have `mesh.volume` returning `0` for 2D surface meshes, regardless of mesh type, and `mesh.enclosed_volume` always returning the enclosed volume of a surface representation of the mesh.

Could rename both, even, and have `enclosed_volume` and `volume_3d`. This way the distinction is clear, the polymorphism is gone, and we can easily cross-reference both properties in the docs for maximum visibility.
